// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP geecc_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
// cf_special1
StringVector cf_special1(const Rcpp::List& items_factor, const Rcpp::List& RNG, IntegerVector t);
RcppExport SEXP geecc_cf_special1(SEXP items_factorSEXP, SEXP RNGSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type items_factor(items_factorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type RNG(RNGSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type t(tSEXP);
    __result = Rcpp::wrap(cf_special1(items_factor, RNG, t));
    return __result;
END_RCPP
}
// cf_intersect6
StringVector cf_intersect6(const StringVector& pop, const StringVector& x);
RcppExport SEXP geecc_cf_intersect6(SEXP popSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const StringVector& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    __result = Rcpp::wrap(cf_intersect6(pop, x));
    return __result;
END_RCPP
}
// cf_setdiff1
StringVector cf_setdiff1(const StringVector& pop, const StringVector& x);
RcppExport SEXP geecc_cf_setdiff1(SEXP popSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const StringVector& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    __result = Rcpp::wrap(cf_setdiff1(pop, x));
    return __result;
END_RCPP
}
