# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('geecc_rcpp_hello_world', PACKAGE = 'geecc')
}

cf_special1 <- function(items_factor, RNG, t) {
    .Call('geecc_cf_special1', PACKAGE = 'geecc', items_factor, RNG, t)
}

cf_intersect6 <- function(pop, x) {
    .Call('geecc_cf_intersect6', PACKAGE = 'geecc', pop, x)
}

cf_setdiff1 <- function(pop, x) {
    .Call('geecc_cf_setdiff1', PACKAGE = 'geecc', pop, x)
}

